# Site settings
name: Abdurrahman Odabashi
title: Abdurrahman Odabashi | Machine Learning Engineer
description: Data-driven problem solver and Machine Learning enthusiast
url: https://odabashi.com/
baseurl: https://63222744.github.io/something/
email: odabasiabdurrahman@gmail.com
logo: https://odabashi.com/img/logo/LogoCircledBlackWhite320px3D.png
# resume: https://odabashi.github.io/resume.pdf
social:
  - title: Email
    url: mailto:odabasiabdurrahman@gmail.com
  - title: Linkedin
    url: https://www.linkedin.com/in/abdurrahmanodabaşı
  # - title: X
  #   url: https://x.com/bchiang7
  # - title: instagram
  #   url: https://instagram.com/bchiang7
  - title: Kaggle
    url: https://www.kaggle.com/odabashi
  - title: Github
    url: https://github.com/odabashi
  - title: Hackerrank
    url: https://www.hackerrank.com/profile/odabashi

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
